version: '3'
services:
  SCUTV:
    image: bestzwei/SCUTV:latest
    container_name: SCUTV
    ports:
      - "8899:80"
    environment:
      - PASSWORD=${PASSWORD:-111111}
    restart: unless-stopped
